name: Setup MQ Dev Environment
description: >-
  Start IBM MQ containers (QM1 + QM2), seed shared test objects,
  and verify the environment is ready.

inputs:
  project-name:
    description: COMPOSE_PROJECT_NAME for container isolation
    required: false
    default: 'mq-dev'
  qm1-rest-port:
    description: Host port for QM1 REST API
    required: false
    default: '9443'
  qm2-rest-port:
    description: Host port for QM2 REST API
    required: false
    default: '9444'
  qm1-mq-port:
    description: Host port for QM1 MQ listener
    required: false
    default: '1414'
  qm2-mq-port:
    description: Host port for QM2 MQ listener
    required: false
    default: '1415'
  verify:
    description: Run mq_verify.sh after seeding
    required: false
    default: 'true'

outputs:
  qm1-rest-url:
    description: QM1 REST API base URL
    value: https://localhost:${{ inputs.qm1-rest-port }}/ibmmq/rest/v2
  qm2-rest-url:
    description: QM2 REST API base URL
    value: https://localhost:${{ inputs.qm2-rest-port }}/ibmmq/rest/v2

runs:
  using: composite
  steps:
    - name: Start MQ containers
      shell: bash
      working-directory: ${{ github.action_path }}/../../..
      env:
        COMPOSE_PROJECT_NAME: ${{ inputs.project-name }}
        QM1_REST_PORT: ${{ inputs.qm1-rest-port }}
        QM2_REST_PORT: ${{ inputs.qm2-rest-port }}
        QM1_MQ_PORT: ${{ inputs.qm1-mq-port }}
        QM2_MQ_PORT: ${{ inputs.qm2-mq-port }}
      run: scripts/mq_start.sh

    - name: Seed MQ objects
      shell: bash
      working-directory: ${{ github.action_path }}/../../..
      env:
        COMPOSE_PROJECT_NAME: ${{ inputs.project-name }}
      run: scripts/mq_seed.sh

    - name: Verify MQ environment
      if: inputs.verify == 'true'
      shell: bash
      working-directory: ${{ github.action_path }}/../../..
      env:
        COMPOSE_PROJECT_NAME: ${{ inputs.project-name }}
        QM1_REST_PORT: ${{ inputs.qm1-rest-port }}
        QM2_REST_PORT: ${{ inputs.qm2-rest-port }}
      run: scripts/mq_verify.sh
