# https://github.com/vergil-project/vergil-actions/blob/develop/.github/workflows/README.md
name: CI

on:
  pull_request:
  workflow_call:
    inputs:
      run-security:
        type: boolean
        default: true
      run-release:
        type: boolean
        default: true

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    uses: vergil-project/vergil-actions/.github/workflows/ci-quality.yml@v2.1
    with:
      language: shell
      container-suffix: base

  security:
    uses: vergil-project/vergil-actions/.github/workflows/ci-security.yml@v2.1
    with:
      language: shell
      run-standards: ${{ inputs.run-release != 'false' }}
      run-security: ${{ inputs.run-security != 'false' }}
      run-codeql: false
      container-suffix: base
    permissions:
      contents: read
      security-events: write
      actions: read

  version:
    uses: vergil-project/vergil-actions/.github/workflows/ci-version-bump.yml@v2.1
    with:
      language: shell
      run-release: ${{ inputs.run-release != 'false' }}
      container-suffix: base
